#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTTP-Headers-Fast
Version  : 0.21
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/HTTP-Headers-Fast-0.21.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/HTTP-Headers-Fast-0.21.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhttp-headers-fast-perl/libhttp-headers-fast-perl_0.21-1.debian.tar.xz
Summary  : 'faster implementation of HTTP::Headers'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-HTTP-Headers-Fast-license
Requires: perl-HTTP-Headers-Fast-man
Requires: perl(ExtUtils::Config)
Requires: perl(ExtUtils::Helpers)
Requires: perl(ExtUtils::InstallPaths)
Requires: perl(Module::Build::Tiny)
BuildRequires : perl(ExtUtils::Config)
BuildRequires : perl(ExtUtils::Helpers)
BuildRequires : perl(ExtUtils::InstallPaths)
BuildRequires : perl(Module::Build::Tiny)

%description
# NAME
HTTP::Headers::Fast - faster implementation of HTTP::Headers
# SYNOPSIS
use HTTP::Headers::Fast;
# and, same as HTTP::Headers.

%package license
Summary: license components for the perl-HTTP-Headers-Fast package.
Group: Default

%description license
license components for the perl-HTTP-Headers-Fast package.


%package man
Summary: man components for the perl-HTTP-Headers-Fast package.
Group: Default

%description man
man components for the perl-HTTP-Headers-Fast package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTTP-Headers-Fast-0.21
mkdir -p %{_topdir}/BUILD/HTTP-Headers-Fast-0.21/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTTP-Headers-Fast-0.21/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTTP-Headers-Fast
cp LICENSE %{buildroot}/usr/share/doc/perl-HTTP-Headers-Fast/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-HTTP-Headers-Fast/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/HTTP/Headers/Fast.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTTP-Headers-Fast/LICENSE
/usr/share/doc/perl-HTTP-Headers-Fast/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/HTTP::Headers::Fast.3
